### ISSUE TITLE
Text Unreadable on Hover in Dark Mode for Tangle Tools Documentation

### ISSUE THREAD

**Issue by ThugOG** [tangle-network/tangle-docs#70]
Description:

I've noticed an issue with the Tangle Tools documentation where the text becomes unreadable when hovering over links or interactive elements in dark mode. Specifically, when viewing the developer blueprints section, the hover effect results in white text on a very light background, making it nearly invisible.

Images: 
<img width="1504" alt="Screenshot 2024-10-13 at 8 50 54 PM" src="https://github.com/user-attachments/assets/7932a13f-c313-4219-b953-2d1d0c085be5">

Steps to Reproduce:
Navigate to the Tangle Tools documentation at docs.tangle.tools/developers/blueprints.
Enable dark mode if it's not already active.
Hover over any link or interactive element within the text content (not images or buttons outside the main text areas).

**Comment by drewstone** [comment]
Thanks for reporting will fix soon.

**Comment by drewstone** [comment]
In the meantime use light mode BTW.
